### ISSUE TITLE
Worldmap panel

### ISSUE THREAD

**Issue by icetail** [DirtyCajunRice/grafana-scripts#15]
I live in the Netherlands. All streams therefore also come from the Netherlands.
Unfortunately worldmap panel indicates that the streams come from "Utah".
The location in "users online" does indicate the correct location.
does the panel only work with location from the United States?

**Comment by samwiseg00** [comment]
You may need to play with the world map settings to get the right display. It uses the region code provided by the GeoIP2 DB. 

Can you tell me which `region_code` is being displayed in the influxdb?
 
We are using the `.subdivisions` method for determining location on the map. 
https://geoip2.readthedocs.io/en/latest/index.html?highlight=subdivisions#geoip2.records.Subdivisions

![2018-08-09_15-49-16](https://user-images.githubusercontent.com/2241731/43922163-ec879818-9beb-11e8-8949-06d828b816bc.png)

**Comment by icetail** [comment]
Region_code "UT" is being inserted.

**Comment by samwiseg00** [comment]
I did a test with a generic IP in the Netherlands and it does seem to only work in the US. I will put some thought into how to expand this to the rest of the world. We will have to change the method in which we use to determine location to accomplish this.

**Comment by samwiseg00** [comment]
I think I figured out a good way to expand this without breaking current functionality.

Can you try this updated [`tautulli.py`](https://gist.github.com/samwiseg00/f616f57d8bef134303ca09b28f2931e6)?

You will need to install a new module `pip3 install Geohash`

Also change grafana to these settings...
![2018-08-09_18-04-28](https://user-images.githubusercontent.com/2241731/43928398-bebd9f3c-9bfe-11e8-827c-4358e5ee1867.png)
![2018-08-09_18-04-42](https://user-images.githubusercontent.com/2241731/43928403-c2ca9026-9bfe-11e8-9425-8c7b4718780b.png)

**Comment by icetail** [comment]
Yes! With this config it is working like a charm!

Had to install "pip install python-geohash"..
was getting this error:

"Traceback (most recent call last):
  File "tautulli.py", line 8, in <module>
    import Geohash
  File "/usr/local/lib/python3.6/dist-packages/Geohash/__init__.py", line 21, in <module>
    from geohash import decode_exactly, decode, encode
ModuleNotFoundError: No module named 'geohash'"

**Comment by samwiseg00** [comment]
Great. I will add that to the `requirements.txt` file. I did notice that the number of clients in the circles seems a bit off. I will do some more tinkering before I push it. Thanks for the speedy testing.

**Comment by samwiseg00** [comment]
I thought about it some more and I think I am going to do it a little bit differently. I am going to use the Lat and Long instead of the geohash. That will remove the dependency. 

I have updated the [gist](https://gist.github.com/samwiseg00/f616f57d8bef134303ca09b28f2931e6) to reflect the changes. 

grafana changes
![2018-08-09_20-51-02](https://user-images.githubusercontent.com/2241731/43933181-36dca9e2-9c16-11e8-8d97-6ce6606dc83d.png)
![2018-08-09_20-51-03](https://user-images.githubusercontent.com/2241731/43933197-429df254-9c16-11e8-963c-1e4424818729.png)

**Comment by xunil75** [comment]
Hi guys, sorry for jumping into this issue but I do have the same problem where I can't see anything on the map. I'm based in Switzerland. The linked "Gists" are not available anymore as well.

Thanks

**Comment by samwiseg00** [comment]
@xunil75 It has bene incorporated into the repo.

https://github.com/DirtyCajunRice/grafana-scripts/blob/master/dashboard/panel_row_worldmap.json

**Comment by xunil75** [comment]
@samwiseg00 then I must have a problem with the retrieved data from Taututtli since I'm not getting the Field "location". Can you please explain me how to include the **panel_row_worldmap.json**?

This is how my Dashboard looks like:

![screencapture](https://user-images.githubusercontent.com/32961904/48116680-22e8ef80-e267-11e8-959e-7427cff56aa6.jpg)

**Comment by samwiseg00** [comment]
Edit the panel json and paste in the json from the repo. 

![unknown](https://user-images.githubusercontent.com/2241731/48116814-3d09da00-e235-11e8-8e0b-2dc702efd7de.png)

**Comment by xunil75** [comment]
@samwiseg00 you're the man!!

![image](https://user-images.githubusercontent.com/32961904/48117570-ed91d100-e269-11e8-85ec-6d0f7f6e6e24.png)

Thank you!
