### ISSUE TITLE
Local streams aren't showing with Tautulli

### ISSUE THREAD

**Issue by jdobbs** [DirtyCajunRice/grafana-scripts#16]
I have several devices streaming internally on the same network as Plex\Tautulli as well as a recently deployed DVR. None of these sessions seem to get imported into InfluxDB. They show up within Tautulli when they're active. Is there anyway to get these streams imported into InfluxDB as well? Even if the IP address is the WAN.

Thanks!

**Comment by samwiseg00** [comment]
I am not understanding what you mean. If it is in tautulli it should be showing up. 
Can you provide some more information?

![2018-09-19_18-16-16](https://user-images.githubusercontent.com/2241731/45782068-30ef9c00-bc38-11e8-96dc-d1611e5ac69f.png)

**Comment by samwiseg00** [comment]
have you looked at this article?

https://github.com/Tautulli/Tautulli-Wiki/wiki/Frequently-Asked-Questions#plex-relay

**Comment by jdobbs** [comment]
Interesting, I have Remote Access disabled so I'd think it would be a direct connection. I'll look further into this avenue. Thanks!

**Comment by jdobbs** [comment]
Quick question though, even if the stream was showing as 127.0.01 or being relayed, shouldn't it still be showing up within the InfluxDB?

**Comment by samwiseg00** [comment]
No problem. 

The screen shot you sent is not allowing it be placed in the DB because the IP address was not found and errored out before it writes it to InfluxDB. I am going to see if I look into finding a better way to deal with IPs that may not be in the DB. 

But the real problem is that you going through the relay. 

Side Note: I would check your firewall and make sure it is either allowing connections to come in or is disabled on the machine you are running plex on. 

Also may want to check the "DNS Rebinding" section in this article. https://support.plex.tv/articles/206225077-how-to-use-secure-server-connections/

**Comment by jdobbs** [comment]
Just my 2cents, maybe rather than not logging or even logging a 127.0.0.1 address, just store it as “Local \ Relay” or something. I’ll look over the other information you pointed too later tonight or tomorrow. Thanks again.

**Comment by jdobbs** [comment]
Looks like I've gotten resolved for the most part. It seems it was the DNS Rebinding issue. I switched from OpenDNS to Google and now internal IP addresses are showing within Tautulli. This now means internal addresses are getting imported into InfluxDB and not erroring out on 127.0.0.1. Thanks for all of the support and work on this!
